# Generated by Django 3.0.4 on 2020-03-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_object', models.URLField()),
                ('metro_name', models.CharField(blank=True, max_length=32)),
                ('metro_distance', models.CharField(blank=True, max_length=50)),
                ('metro_distance_number', models.IntegerField(blank=True)),
                ('total_square', models.CharField(blank=True, max_length=32)),
                ('living_square', models.CharField(blank=True, max_length=32)),
                ('floor_number', models.CharField(blank=True, max_length=32)),
                ('floor_total', models.CharField(blank=True, max_length=32)),
                ('count_room', models.CharField(blank=True, max_length=32)),
                ('material', models.CharField(blank=True, max_length=32)),
                ('balcony_type', models.CharField(blank=True, max_length=32)),
                ('is_home_appliances', models.CharField(blank=True, max_length=32)),
                ('is_furniture', models.CharField(blank=True, max_length=32)),
                ('year_public', models.CharField(blank=True, max_length=32)),
                ('month_public', models.CharField(blank=True, max_length=32)),
                ('day_public', models.CharField(blank=True, max_length=32)),
                ('time_public', models.CharField(blank=True, max_length=16)),
                ('cost', models.CharField(blank=True, max_length=32)),
                ('currency', models.CharField(blank=True, max_length=32)),
                ('street', models.CharField(max_length=32)),
                ('house_number', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(blank=True, max_length=32)),
                ('area_city', models.CharField(blank=True, max_length=32)),
                ('advertising_object', models.CharField(blank=True, max_length=70)),
                ('category', models.ManyToManyField(to='realtyapp.Category')),
            ],
        ),
    ]
