# Generated by Django 3.0.4 on 2020-04-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('telefone', models.CharField(blank=True, max_length=16)),
            ],
        ),
    ]
